version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10

- package-ecosystem: "dotnet-sdk"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "wednesday"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily